-- AlterTable
ALTER TABLE "locations" ADD COLUMN     "avgHouseholdIncome" DECIMAL(8,2),
ADD COLUMN     "carOwnership" DECIMAL(4,1),
ADD COLUMN     "carOwnershipVsNational" DECIMAL(4,1),
ADD COLUMN     "carParkPrice" DECIMAL(5,2),
ADD COLUMN     "evCharging" BOOLEAN DEFAULT false,
ADD COLUMN     "evChargingSpaces" INTEGER,
ADD COLUMN     "facebook" TEXT,
ADD COLUMN     "facebookRating" DECIMAL(2,1),
ADD COLUMN     "facebookReviews" INTEGER,
ADD COLUMN     "facebookVotes" INTEGER,
ADD COLUMN     "familiesPercent" DECIMAL(4,1),
ADD COLUMN     "footfall" INTEGER,
ADD COLUMN     "googleRating" DECIMAL(2,1),
ADD COLUMN     "googleReviews" INTEGER,
ADD COLUMN     "googleVotes" INTEGER,
ADD COLUMN     "homeownership" DECIMAL(4,1),
ADD COLUMN     "homeownershipVsNational" DECIMAL(4,1),
ADD COLUMN     "incomeVsNational" DECIMAL(6,2),
ADD COLUMN     "instagram" TEXT,
ADD COLUMN     "medianAge" INTEGER,
ADD COLUMN     "population" INTEGER,
ADD COLUMN     "retailSpace" INTEGER,
ADD COLUMN     "retailers" INTEGER,
ADD COLUMN     "seniorsPercent" DECIMAL(4,1),
ADD COLUMN     "seoKeywords" JSONB,
ADD COLUMN     "tiktok" TEXT,
ADD COLUMN     "topPages" JSONB,
ADD COLUMN     "youtube" TEXT;
