import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const locationId = "cmid0kv0r01obmtpuinuwnn2n";

const tenants = [
    // F&B
    { name: "Wingstop", cat: "Food & Beverage" },
    { name: "Raykdi", cat: "Food & Beverage" },
    { name: "Love Churros London", cat: "Food & Beverage" },
    { name: "Bill's", cat: "Food & Beverage" },
    { name: "Maki & Ramen", cat: "Food & Beverage" },
    { name: "Tamatanga", cat: "Food & Beverage" },
    { name: "Hotel Chocolat", cat: "Food & Beverage" },
    { name: "Bubbleology", cat: "Food & Beverage" },
    { name: "Starbucks", cat: "Food & Beverage" },
    { name: "PizzaExpress", cat: "Food & Beverage" },
    { name: "Pho", cat: "Food & Beverage" },
    { name: "Nando's", cat: "Food & Beverage" },
    { name: "McDonald's", cat: "Food & Beverage" },
    { name: "Boost", cat: "Food & Beverage" },
    { name: "Turtle Bay", cat: "Food & Beverage" },
    { name: "Frankie & Benny's", cat: "Food & Beverage" },
    { name: "SOHO Coffee", cat: "Food & Beverage" },
    { name: "Slim Chickens", cat: "Food & Beverage" },
    { name: "YO!", cat: "Food & Beverage" },
    { name: "Krispy Kreme", cat: "Food & Beverage" },
    { name: "Millie's Cookies", cat: "Food & Beverage" },
    { name: "Bakers and Baristas", cat: "Food & Beverage" },
    { name: "Greggs", cat: "Food & Beverage" },
    { name: "Auntie Anne's Bakery", cat: "Food & Beverage" },
    { name: "Zizzi", cat: "Food & Beverage" },
    { name: "Bubble CiTea", cat: "Food & Beverage" },
    { name: "Wagamama", cat: "Food & Beverage" },
    { name: "American Candy", cat: "Food & Beverage" },
    
    // Leisure
    { name: "Castore", cat: "Sports & Outdoors" },
    { name: "The Gym Group", cat: "Leisure" },
    { name: "JD Sports", cat: "Sports & Outdoors", anchor: true },
    { name: "Treetop Golf", cat: "Leisure" },
    { name: "Runners Need", cat: "Sports & Outdoors" },
    { name: "Cotswold Outdoor Outlet", cat: "Sports & Outdoors" },
    { name: "Trespass", cat: "Sports & Outdoors" },
    { name: "Showcase Cinema de Lux", cat: "Leisure", anchor: true },
    { name: "Social Climbing", cat: "Leisure" },
    
    // Shops
    { name: "John Lewis & Partners", cat: "Department Store", anchor: true },
    { name: "Apple", cat: "Electronics & Technology", anchor: true },
    { name: "Zara", cat: "Fashion & Apparel", anchor: true },
    { name: "H&M", cat: "Fashion & Apparel", anchor: true },
    { name: "Primark", cat: "Fashion & Apparel", anchor: true },
    { name: "Boots", cat: "Health & Beauty", anchor: true },
    { name: "Superdrug", cat: "Health & Beauty" },
    { name: "Nomination", cat: "Jewellery & Accessories" },
    { name: "Sell Your Car 2 Jack", cat: "Services" },
    { name: "Austen and Blake", cat: "Jewellery & Accessories" },
    { name: "Mamas & Papas", cat: "Kids & Toys" },
    { name: "Heart of England Training", cat: "Services" },
    { name: "SET", cat: "Gifts & Cards" },
    { name: "Cochani", cat: "Fashion & Apparel" },
    { name: "Space NK", cat: "Health & Beauty" },
    { name: "Mango", cat: "Fashion & Apparel" },
    { name: "Baggage World", cat: "Fashion & Apparel" },
    { name: "Sunglass Hut", cat: "Jewellery & Accessories" },
    { name: "Mobilise Group", cat: "Services" },
    { name: "Card Factory", cat: "Gifts & Cards" },
    { name: "Swarovski", cat: "Jewellery & Accessories" },
    { name: "The Works", cat: "Books, Stationery & News" },
    { name: "Luke 1977", cat: "Fashion & Apparel" },
    { name: "Ernest Jones", cat: "Jewellery & Accessories" },
    { name: "Ann Summers", cat: "Fashion & Apparel" },
    { name: "Breitling", cat: "Jewellery & Accessories" },
    { name: "BOSS", cat: "Fashion & Apparel" },
    { name: "Typo", cat: "Gifts & Cards" },
    { name: "Suit Direct", cat: "Fashion & Apparel" },
    { name: "Menkind", cat: "Gifts & Cards" },
    { name: "Better Brows", cat: "Health & Beauty" },
    { name: "Jo Malone London", cat: "Health & Beauty" },
    { name: "Reiss", cat: "Fashion & Apparel" },
    { name: "Warren James", cat: "Jewellery & Accessories" },
    { name: "The Perfume Shop", cat: "Health & Beauty" },
    { name: "Next", cat: "Fashion & Apparel", anchor: true },
    { name: "New Look", cat: "Fashion & Apparel" },
    { name: "Damaged Society", cat: "Fashion & Apparel" },
    { name: "Lovisa", cat: "Jewellery & Accessories" },
    { name: "Yankee Candle", cat: "Gifts & Cards" },
    { name: "Eurochange", cat: "Financial Services" },
    { name: "The Body Shop", cat: "Health & Beauty" },
    { name: "River Island", cat: "Fashion & Apparel" },
    { name: "Levi's", cat: "Fashion & Apparel" },
    { name: "Goldsmiths", cat: "Jewellery & Accessories" },
    { name: "Lush", cat: "Health & Beauty" },
    { name: "Claire's", cat: "Jewellery & Accessories" },
    { name: "Clarendon Fine Art Leicester", cat: "Gifts & Cards" },
    { name: "ISmash", cat: "Services" },
    { name: "Therapie Clinic", cat: "Health & Beauty" },
    { name: "Pandora", cat: "Jewellery & Accessories" },
    { name: "Laser Clinics UK", cat: "Health & Beauty" },
    { name: "Skechers", cat: "Fashion & Apparel" },
    { name: "Samsung", cat: "Electronics & Technology" },
    { name: "Beaverbrooks", cat: "Jewellery & Accessories" },
    { name: "The WATCH Lab", cat: "Services" },
    { name: "Clarks", cat: "Fashion & Apparel" },
    { name: "Quiz", cat: "Fashion & Apparel" },
    { name: "Waterstones", cat: "Books, Stationery & News" },
    { name: "Vodafone", cat: "Services" },
    { name: "Vision Express", cat: "Health & Beauty" },
    { name: "The Fragrance Shop", cat: "Health & Beauty" },
    { name: "Rebel", cat: "Fashion & Apparel" },
    { name: "Post Office", cat: "Services" },
    { name: "Moss", cat: "Fashion & Apparel" },
    { name: "Flying Tiger Copenhagen", cat: "Gifts & Cards" },
    { name: "Clintons", cat: "Gifts & Cards" },
    { name: "Foot Locker", cat: "Fashion & Apparel" },
    { name: "Sky", cat: "Services" },
    { name: "Urban Outfitters", cat: "Fashion & Apparel" },
    { name: "The Car Wash Company", cat: "Services" },
    { name: "schuh", cat: "Fashion & Apparel" },
    { name: "Clarins", cat: "Health & Beauty" },
    { name: "3 (Three)", cat: "Services" },
    { name: "TAG Heuer", cat: "Jewellery & Accessories" },
    { name: "Timberland", cat: "Fashion & Apparel" },
    { name: "Superdry", cat: "Fashion & Apparel" },
    { name: "Smiggle", cat: "Gifts & Cards" },
    { name: "O2", cat: "Services" },
    { name: "Build-a-Bear", cat: "Gifts & Cards" },
    { name: "Holland & Barrett", cat: "Health & Beauty" }
];

async function main() {
    console.log(`🚀 Injecting ${tenants.length} deep-verified tenants into Highcross...`);
    for (const t of tenants) {
        await prisma.tenant.create({
            data: {
                locationId,
                name: t.name,
                category: t.cat,
                isAnchorTenant: t.anchor || false
            }
        });
    }
    console.log("✅ Highcross Depth Enrichment Complete.");
}

main().catch(console.error).finally(() => prisma.$disconnect());
