import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    const totalLocations = await prisma.location.count();
    const shoppingCentres = await prisma.location.count({ where: { type: 'SHOPPING_CENTRE' } });
    const retailParks = await prisma.location.count({ where: { type: 'RETAIL_PARK' } });
    const outletCentres = await prisma.location.count({ where: { type: 'OUTLET_CENTRE' } });
    const highStreets = await prisma.location.count({ where: { type: 'HIGH_STREET' } });

    // Total parking spaces (sum of all known)
    const aggregateResult = await prisma.location.aggregate({
        _sum: {
            parkingSpaces: true,
            footfall: true,
            retailSpace: true,
            vacantUnits: true,
        }
    });

    const totalTenants = await prisma.tenant.count();

    // Complexity indicators
    const missingWebsites = await prisma.location.count({ where: { website: null } });
    const withWebsite = await prisma.location.count({ where: { website: { not: null } } });

    const missingSocials = await prisma.location.count({
        where: {
            instagram: null,
            facebook: null,
            twitter: null,
            tiktok: null,
            youtube: null
        }
    });

    // "Poorly managed" can be inferred by checking for autogenerated or directory sites if we have that logic, 
    // but for now we can check likely low-quality patterns or just use the missing website metric as the "poor info" proxy.
    // In the context of the user request, "poorly managed websites" might refer to what we saw in the verification report (wheree.com etc).
    // Let's count wheree.com sites specifically as they were called out in the report as "borderline".
    const directorySites = await prisma.location.count({
        where: {
            website: { contains: 'wheree.com' }
        }
    });

    // Calculate "Total Datapoints" roughly
    // Locations have ~100 fields. Tenants have ~10. Categories ~5.
    // This is a marketing number, so we estimate based on schema + rows.
    const locationFields = 90; // approx from schema
    const tenantFields = 10;
    const totalDatapoints = (totalLocations * locationFields) + (totalTenants * tenantFields);

    console.log(JSON.stringify({
        counts: {
            totalLocations,
            shoppingCentres,
            retailParks,
            outletCentres,
            highStreets,
            totalTenants
        },
        sums: {
            totalParkingSpaces: aggregateResult._sum.parkingSpaces,
            totalFootfall: aggregateResult._sum.footfall,
            totalRetailSpace: aggregateResult._sum.retailSpace,
            totalVacantUnits: aggregateResult._sum.vacantUnits
        },
        quality: {
            missingWebsites,
            withWebsite,
            missingSocials,
            directorySites // "borderline/poor"
        },
        marketing: {
            totalDatapointsEstimate: totalDatapoints
        }
    }, null, 2));
}

main()
    .catch(e => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
